[package]
name = "marlin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1", features = ["full"]}
mini-redis = "0.4"
winit = "0.27"
env_logger = "0.10"
wgpu = "0.15"
bytemuck = { version = "1.12", features = [ "derive" ] }

hebrides = "0.1.45"
